GitPjt/force-app/main/default/objects/CustumObj1__c/CustumObj1__c.object-meta.xml
<CustomObject>
    <label>CustumObj1</label>
    <nameField>
        <label>CustumObj1名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

GitPjt/force-app/main/default/objects/CustumObj1__c/fields/CustomDate1__c.field-meta.xml
<CustomField>
    <fullName>CustomDate1__c</fullName>
    <label>CustomDate1</label>
    <type>Date</type>
</CustomField>

GitPjt/force-app/main/default/objects/CustumObj1__c/fields/CustomPicklst1__c.field-meta.xml
<CustomField>
    <fullName>CustomPicklst1__c</fullName>
    <label>CustomPicklst1</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>値1</fullName>
            </value>
            <value>
                <fullName>値2</fullName>
            </value>
            <value>
                <fullName>値3</fullName>
            </value>
            <value>
                <fullName>値4</fullName>
            </value>
            <value>
                <fullName>値5</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

GitPjt/force-app/main/default/objects/CustumObj1__c/fields/CustomText1__c.field-meta.xml
<CustomField>
    <fullName>CustomText1__c</fullName>
    <label>CustomText1</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

GitPjt/force-app/main/default/classes/CustumObj1Controller.cls
public with sharing class CustumObj1Controller {
    @AuraEnabled (cacheable=true)
    public static CustumObj1__c getCustumObj1(final Id recordId) {
        CustumObj1__c cb1 = [Select id, Name, RecordTypeId,
                             CustomDate1__c, CustomPicklst1__c, CustomText1__c
                             From CustumObj1__c
                             where Id = :recordId];
        return cb1;
    }

    @AuraEnabled
    public static void saveCustumObj1(final CustumObj1__c cb1) {
        System.debug('cb1 : ' + cb1);
        upsert cb1;
    }
}